name: Build and Push with Spring Boot Build Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build image with multiple tags
      - name: Build Spring Boot Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_HUB_USERNAME }}/ai-demo

          mvn spring-boot:build-image \
            -Dspring-boot.build-image.imageName=$IMAGE_NAME:latest

          # Tag with commit SHA and latest
          docker tag $IMAGE_NAME:latest

          # Push all tags
          docker push $IMAGE_NAME:latest
